### ISSUE TITLE
issues building on ubuntu 19.10

### ISSUE THREAD

**Issue by currowth** [vinsonlee/iomemory-vsl4#2]
I am getting the below error when i try to build on ubuntu 19.10. I am also getting similar error when i try to build from the sandisk source iomemory-vsl4_4.3.7.1205-1.0.tar

/home/temp/iomemory-vsl4/driver_source/ktime.c: In function ‘fusion_getwallclocktime’:

/home/temp/iomemory-vsl4/driver_source/ktime.c:126:26: error: implicit declaration of function ‘current_kernel_time’; did you mean ‘core_kernel_text’? [-Werror=implicit-function-declarati
on]

     struct timespec ts = current_kernel_time();

                          ^~~~~~~~~~~~~~~~~~~

                          core_kernel_text

/home/temp/iomemory-vsl4/driver_source/ktime.c:126:26: error: invalid initializer

cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:286: /home/temp/iomemory-vsl4/driver_source/ktime.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:1614: _module_/home/temp/iomemory-vsl4/driver_source] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-5.0.0-38-generic'
make[1]: *** [Makefile:84: modules] Error 2
make[1]: Leaving directory '/home/temp/iomemory-vsl4/driver_source'
ERROR:
make: *** [debian/rules:102: build-arch-stamp] Error 1
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

**Comment by vinsonlee** [comment]
Ubuntu 19.10 uses Linux kernel 5.3.

current_kernel_time was removed in Linux kernel 4.20 commit 976516404ff3fab2a8caa8bd6f5efc1437fed0b8 ("y2038: remove unused time interfaces").

iomemory-vsl4-4.3.7 does not have support for latest Linux kernels.

**Comment by currowth** [comment]
Do you think its possible to port the changes made for vsl3 onto vsl4 made by snuf?
https://github.com/snuf/iomemory-vsl
